# =======================================
# CONFIGURAÇÃO DO BANCO DE DADOS (PostgreSQL)
# =======================================
# URL de conexão: aponta para o banco 'futime_db' na sua máquina local (localhost)
spring.datasource.url=jdbc:postgresql://localhost:5432/futime_db

# Usuário padrão do PostgreSQL
spring.datasource.username=postgres

# ATENÇÃO: Substitua pela senha que você criou na instalação do PostgreSQL
spring.datasource.password=${DB_PASSWORD}


# =======================================
# CONFIGURAÇÃO DO HIBERNATE (JPA)
# =======================================
# 'update': O Hibernate tentará atualizar o banco (criar/alterar tabelas) com base nas suas classes @Entity. Ótimo para desenvolvimento.
spring.jpa.hibernate.ddl-auto=update

# Mostra no console o SQL que o Hibernate está executando. Excelente para debugar.
spring.jpa.show-sql=true

# Formata o SQL mostrado no console para ficar mais legível.
spring.jpa.properties.hibernate.format_sql=true
